# DUMP DB
# docker exec -t your-db-container pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
# cat your_dump.sql | docker exec -i your-db-container psql -U postgres
version: '3.7'
services:
  database:
    container_name: database
    image: postgres:12
    volumes:
      - directus-db:/var/lib/postgresql/data
    networks:
      - directus
    ports:
      - '5432:5432'  
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    build:
      context: ./
      target: ${NODE_ENV:-development}
    volumes:
      - ./:/directus
    restart: always
    ports:
      - 8055:8055
      - 8080:8080
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@root.com'
      ADMIN_PASSWORD: 'directus'

networks:
  directus:

volumes: 
  directus-db: